name: Lint
on: [push, pull_request]

jobs:
  lint:
    name: Node.js
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: ["14.x"]

    steps:
      - name: Checkout https://github.com/${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          persist-credentials: false

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1.4.6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run linter
        run: npx --no-install jshint@2.12.0 .
